#!/bin/bash
echo -e "Sisesta kasutaja vanus: \c"
read vanus

if [[ $vanus -gt 0 && $vanus -lt 11 ]]; then
    echo "Oled laps"
elif [[ $vanus -ge 11 && $vanus -lt 18 ]]; then
    echo "Oled nooruk"
elif [[ $vanus -ge 18 && $vanus -lt 63 ]]; then
    echo "Oled täiskasvanu"
elif [[ $vanus -ge 63 ]]; then
    echo "Oled seenior"
else
    echo "Vigane sisend!"
fi
