#!/bin/bash
#skripti eesmärk on väljastada mitu päeva antud hetkel masin on tööl

#leian masina nime
host=$(hostname)

#leian serveri tööajaga seotud info ja lõikan sealt välja ainult päevade arvu
days=$(uptime | grep -Eo "up ([0-9]+) day" | awk '{print $2}')

echo "Masin $host on töötanud $days päev."
