#!/bin/bash
#skript loob lause, mis sisaldab aastat ja Eesti presidendi nime.

aasta=2021
president="Alar Karis"
lause_keskosa=". aastal valiti Eesti presidendiks "
lause=$aasta$lause_keskosa$president

echo $lause

