#!/bin/bash

echo -e "Sisesta ridade arv: \c"
read ridade_arv
echo -e "Sisesta tarnide arv reas: \c"
read tarnide_arv

for ((r=1; r<=ridade_arv; r++))
do
  echo -n "$r. "
  for ((t=1; t<=tarnide_arv; t++))
  do
    echo -n "*"
  done
  echo ""
done
